version: '3.8'
services:
  cache:
    container_name: redis-local
    image: redis:6.2-alpine
    ports:
      - '6379:6379'
    command: redis-server --save 20 1 --loglevel warning
    volumes:
      - cache:/data

  mongo:
    container_name: mongo-local
    image: mongo
    ports:
      - '27017:27017'
    environment:
      MONGO_INITDB_ROOT_USERNAME: pedometer
      MONGO_INITDB_ROOT_PASSWORD: pedometer

volumes:
  cache:
    driver: local
